name: permission
description: A new Flutter plugin for permission.
version: 0.1.1
author: Lewis <once10301@gmail.com>
homepage: https://github.com/once10301/permission

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.permission
    pluginClass: PermissionPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
